const TWITTER_CONSUMER_KEY= 'CONSUMER KEU';
const TWITTER_CONSUMER_SECRET= 'CONSUMER SECRET';
const TWITTER_BEARER_TOKEN = 'BEARER TOKEN'

module.exports = {
    TWITTER_CONSUMER_KEY,
    TWITTER_CONSUMER_SECRET,
    TWITTER_BEARER_TOKEN
}